$everstring=function(a,g,b){var l=Node.prototype;b=NodeList.prototype;var c=[].forEach,e=a.createElement("i");b.forEach=c;g.on=l.on=function(a,b){this.addEventListener(a,b,!1);return this};b.on=function(a,b){this.forEach(function(e){e.on(a,b)});return this};g.trigger=l.trigger=function(b,e){var c=a.createEvent("HTMLEvents");c.initEvent(b,!0,!0);c.data=e||{};c.eventName=b;c.target=this;this.dispatchEvent(c);return this};b.trigger=function(a){this.forEach(function(b){b.trigger(a)});return this};b=function(b){b=
a.querySelectorAll(b||"");return 1==b.length?b[0]:b};b.on=l.on.bind(e);b.trigger=l.trigger.bind(e);return b}(document,this);
function everstringInjectPartnerJs(a){everstringInjectImg("idsync.rlcdn.com/386216.gif?partner_uid="+a);everstringInjectImg("su.addthis.com/red/usync?pid=11160&puid="+a+"&url=https%3A%2F%2Fnova.everstring.com%2Fsync%2Fo%2F1%3Fidsite%3D845224%26at_uid%3D%7B%7Buid%7D%7D%26es_id%3D"+a);0<=window.location.href.indexOf("www.appstreaming.autodesk.com/install/app/")?(everstringInjectImg("www.facebook.com/tr?ev=6023732176999&cd[value]=0.00&cd[currency]=USD&noscript=1"),everstringInjectImg("www.googleadservices.com/pagead/conversion/969094066/?label=UAENCKrEolsQsueMzgM&guid=ON&script=0"),everstringInjectImg("api.adsymptotic.com/api/s/trackconversion?_pid=12300&_psign=215c7a9dc6ce72c4675c6db898a9e0a7&_aid=2282&_lbl=CT&_pc_ev_tp=autodesk_trialdownload")):
(window._es_fbq&&window._es_fbq[0][1]&&window._es_fbq[0][2]&&everstringInjectImg("www.facebook.com/tr?ev="+_es_fbq[0][1]+"&cd[value]="+_es_fbq[0][2].value+"&cd[currency]="+_es_fbq[0][2].currency+"&noscript=1"),window._es_g_track_id&&window._es_g_track_label&&everstringInjectImg("www.googleadservices.com/pagead/conversion/"+window._es_g_track_id+"/?label="+window._es_g_track_label+"&guid=ON&script=0"))}
function everstringInjectJsNoSSL(a){var g=document,b=g.createElement("script"),g=g.getElementsByTagName("script")[0];b.type="text/javascript";b.defer=!0;b.async=!0;b.src="http://"+a;g.parentNode.insertBefore(b,g)}function everstringInjectJs(a){var g="https:"==document.location.protocol?"https://":"http://",b=document,l=b.createElement("script"),b=b.getElementsByTagName("script")[0];l.type="text/javascript";l.defer=!0;l.async=!0;l.src=g+a;b.parentNode.insertBefore(l,b)}
function everstringInjectImg(a){var g="https:"==document.location.protocol?"https://":"http://",b=document,l=b.createElement("img");b.getElementsByTagName("body");l.src=g+a;a=document.createElement("img");a.setAttribute("src",l.src);a.setAttribute("style","display:none;");$everstring("body").appendChild(a)}
(function(){var a=window.location.href;"#"==a.substr(a.length-1,1)&&(a=a.substr(0,a.length-1));"/"==a.substr(a.length-1,1)&&(a=a.substr(0,a.length-1));var g=document.createElement("script");g.type="text/javascript";g.src="http://www.everstring.com/track/trackset/trackquery?siteId="+Piwik.getAsyncTracker().getSiteId()+"&url="+a;document.getElementsByTagName("head")[0].appendChild(g)});
function trackEmail(){$everstring("input").onblur=function(){var a=$everstring(this).val();if(/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/.test(a)){var g=$everstring(this).parents("form"),b="",l="",c="",e="",t="";g?g.submit(function(){g.find("input:text").each(function(a){a=$everstring(this).attr("name").toLowerCase();0<=a.indexOf("firstname")?b=$everstring(this).val():0<=a.indexOf("lastname")?l=$everstring(this).val():0<=a.indexOf("company")?c=$everstring(this).val():0<=a.indexOf("phone")?
e=$everstring(this).val():0<=a.indexOf("title")&&(t=$everstring(this).val())});_esaq.push(["trackLead","signup",{email:a,firstname:b,lastname:l,company:c,phone:e,title:t}])}):_esaq.push(["trackLead","signup",{email:a}])}}}"object"!==typeof JSON2&&(JSON2={});
(function(){function a(a){return 10>a?"0"+a:a}function g(a){c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=V[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(c,l){var n,B,r,N,H=e,v,m=l[c];m&&"object"===typeof m&&(n=m,r=Object.prototype.toString.apply(n),m="[object Date]"===r?isFinite(n.valueOf())?n.getUTCFullYear()+"-"+a(n.getUTCMonth()+1)+"-"+a(n.getUTCDate())+"T"+a(n.getUTCHours())+":"+a(n.getUTCMinutes())+":"+a(n.getUTCSeconds())+
"Z":null:"[object String]"===r||"[object Number]"===r||"[object Boolean]"===r?n.valueOf():"[object Array]"!==r&&"function"===typeof n.toJSON?n.toJSON(c):n);"function"===typeof z&&(m=z.call(l,c,m));switch(typeof m){case "string":return g(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";e+=t;v=[];if("[object Array]"===Object.prototype.toString.apply(m)){N=m.length;for(n=0;n<N;n+=1)v[n]=b(n,m)||"null";r=0===v.length?"[]":
e?"[\n"+e+v.join(",\n"+e)+"\n"+H+"]":"["+v.join(",")+"]";e=H;return r}if(z&&"object"===typeof z)for(N=z.length,n=0;n<N;n+=1)"string"===typeof z[n]&&(B=z[n],(r=b(B,m))&&v.push(g(B)+(e?": ":":")+r));else for(B in m)Object.prototype.hasOwnProperty.call(m,B)&&(r=b(B,m))&&v.push(g(B)+(e?": ":":")+r);r=0===v.length?"{}":e?"{\n"+e+v.join(",\n"+e)+"\n"+H+"}":"{"+v.join(",")+"}";e=H;return r}}var l=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e,t,V={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},z;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(a,c,n){var g;t=e="";if("number"===typeof n)for(g=0;g<n;g+=1)t+=" ";else"string"===typeof n&&(t=n);if((z=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON2.stringify");return b("",{"":a})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(a,b){function c(a,e){var g,l,m=a[e];if(m&&"object"===typeof m)for(g in m)Object.prototype.hasOwnProperty.call(m,
g)&&(l=c(m,g),void 0!==l?m[g]=l:delete m[g]);return b.call(a,e,m)}var e;a=String(a);l.lastIndex=0;l.test(a)&&(a=a.replace(l,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?c({"":e},""):e;throw new SyntaxError("JSON2.parse");})})();
"object"!==typeof _esaq&&(_esaq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function a(a){return"undefined"!==typeof a}function g(a){return"object"===typeof a}function b(a){return"string"===typeof a||a instanceof String}function l(){var a,L,c;for(a=0;a<arguments.length;a+=1)c=arguments[a],L=c.shift(),b(L)?I[L].apply(I,c):L.apply(I,c)}function c(a,b,c,h){if(a.addEventListener)return a.addEventListener(b,c,h),!0;if(a.attachEvent)return a.attachEvent("on"+b,c);a["on"+b]=c}function e(a,b){var c="",h,e;for(h in Y)Object.prototype.hasOwnProperty.call(Y,
h)&&(e=Y[h][a],"function"===typeof e&&(c+=e(b)));return c}function t(){var a;if(!aa)for(aa=!0,e("load"),a=0;a<pa.length;a++)pa[a]();return!0}function V(a,b){var c=k.createElement("script");c.type="text/javascript";c.src=a;c.readyState?c.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)c.onreadystatechange=null,b()}:c.onload=b;k.getElementsByTagName("head")[0].appendChild(c)}function z(){var a="";try{a=f.top.document.referrer}catch(b){if(f.parent)try{a=f.parent.document.referrer}catch(c){a=
""}}""===a&&(a=k.referrer);return a}function Ea(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function X(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function n(a,b){var c=(new RegExp("[\\?&#]"+b+"=([^&#]*)")).exec(a);return c?Ga(c[1]):""}function B(a){var b=function(a,b){return a<<b|a>>>32-b},c=function(a){var b="",c,e;for(c=7;0<=c;c--)e=a>>>4*c&15,b+=e.toString(16);return b},h,e,g=[],k=1732584193,n=4023233417,f=2562383102,l=271733878,m=3285377520,p,u,q,t,r,D=[];a=
Ka(w(a));p=a.length;for(h=0;h<p-3;h+=4)e=a.charCodeAt(h)<<24|a.charCodeAt(h+1)<<16|a.charCodeAt(h+2)<<8|a.charCodeAt(h+3),D.push(e);switch(p&3){case 0:h=2147483648;break;case 1:h=a.charCodeAt(p-1)<<24|8388608;break;case 2:h=a.charCodeAt(p-2)<<24|a.charCodeAt(p-1)<<16|32768;break;case 3:h=a.charCodeAt(p-3)<<24|a.charCodeAt(p-2)<<16|a.charCodeAt(p-1)<<8|128}for(D.push(h);14!==(D.length&15);)D.push(0);D.push(p>>>29);D.push(p<<3&4294967295);for(a=0;a<D.length;a+=16){for(h=0;16>h;h++)g[h]=D[a+h];for(h=
16;79>=h;h++)g[h]=b(g[h-3]^g[h-8]^g[h-14]^g[h-16],1);e=k;p=n;u=f;q=l;t=m;for(h=0;19>=h;h++)r=b(e,5)+(p&u|~p&q)+t+g[h]+1518500249&4294967295,t=q,q=u,u=b(p,30),p=e,e=r;for(h=20;39>=h;h++)r=b(e,5)+(p^u^q)+t+g[h]+1859775393&4294967295,t=q,q=u,u=b(p,30),p=e,e=r;for(h=40;59>=h;h++)r=b(e,5)+(p&u|p&q|u&q)+t+g[h]+2400959708&4294967295,t=q,q=u,u=b(p,30),p=e,e=r;for(h=60;79>=h;h++)r=b(e,5)+(p^u^q)+t+g[h]+3395469782&4294967295,t=q,q=u,u=b(p,30),p=e,e=r;k=k+e&4294967295;n=n+p&4294967295;f=f+u&4294967295;l=l+q&
4294967295;m=m+t&4294967295}r=c(k)+c(n)+c(f)+c(l)+c(m);return r.toLowerCase()}function r(a,b,c){if("translate.googleusercontent.com"===a)""===c&&(c=b),b=n(b,"u"),a=X(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=k.links[0].href,a=X(b);return[a,b,c]}function N(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function H(c){c=c&&c.text?c.text:c;if(!b(c)){var e=k.getElementsByTagName("title");e&&a(e[0])&&
(c=e[0].text)}return c}function v(a,b){if(b)return b;"webls.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function m(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idsite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(k.referrer);if(b){if(b[1]!==String(a))return!1;f.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=f.name.split("###");return 3===a.length&&"Piwik_Overlay"===a[0]}function ib(a,b,c){var e=f.name.split("###"),g=e[1],k=e[2],n=v(a,b);V(n+"plugins/Overlay/client/client.js?v=1",
function(){Piwik_Overlay_Client.initialize(n,c,g,k)})}function fa(l,t){function v(d,a,b,c,e,g){if(!T){var h;b&&(h=new Date,h.setTime(h.getTime()+b));k.cookie=d+"="+w(a)+(b?";expires="+h.toGMTString():"")+";path="+(c||"/")+(e?";domain="+e:"")+(g?";secure":"")}}function h(d){return T?0:(d=(new RegExp("(^|;)[ ]*"+d+"=([^;]*)")).exec(k.cookie))?Ga(d[2]):0}function S(d){var a;return La?(a=/#.*/,d.replace(a,"")):d}function V(d){var a,b,c;for(a=0;a<ga.length;a++){b=N(ga[a].toLowerCase());if(d===b)return!0;
if("."===b.slice(0,1)){if(d===b.slice(1))return!0;c=d.length-b.length;if(0<c&&d.slice(c)===b)return!0}}return!1}function I(d){var a=new Image(1,1);a.onload=function(){A=0};a.src=ba+(0>ba.indexOf("?")?"?":"&")+d}function Y(d){try{var a=f.XMLHttpRequest?new f.XMLHttpRequest:f.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;a.open("POST",ba,!0);a.onreadystatechange=function(){4===this.readyState&&200!==this.status&&I(d)};a.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
a.send(d)}catch(b){I(d)}}function C(d,a){var b=new Date;ra||("POST"===Ma?Y(d):I(d),sa=b.getTime()+a)}function K(d){return Na+d+"."+R+"."+Oa}function ea(){if(T)return"0";if(!a(x.cookieEnabled)){var d=K("testcookie");v(d,"1");return"1"===h(d)?"1":"0"}return x.cookieEnabled?"1":"0"}function p(){Oa=Pa((O||ta)+(P||"/")).slice(0,4)}function u(){var d=K("cvar"),d=h(d);return d.length&&(d=JSON2.parse(d),g(d))?d:{}}function q(){ua=(new Date).getTime()}function fa(d,a,b,c,e,h){v(K("id"),d+"."+a+"."+b+"."+c+
"."+e+"."+h,Qa,P,O)}function qa(){var d=Math.round((new Date).getTime()/1E3),a=h(K("id"));a?(d=a.split("."),d.unshift("0")):(va||(va=Pa((x.userAgent||"")+(x.platform||"")+JSON2.stringify(Q)+d).slice(0,16)),d=["1",va,d,0,d,"",""]);return d}function D(){var d=h(K("ref"));if(d.length)try{if(d=JSON2.parse(d),g(d))return d}catch(a){}return["","",0,""]}function Ha(){var d=T;T=!1;v(K("id"),"",-86400,P,O);v(K("ses"),"",-86400,P,O);v(K("cvar"),"",-86400,P,O);v(K("ref"),"",-86400,P,O);T=d}function Ia(d){if(d&&
g(d)){var a=[],b;for(b in d)Object.prototype.hasOwnProperty.call(d,b)&&a.push(b);b={};a.sort();var c=a.length,e;for(e=0;e<c;e++)b[a[e]]=d[a[e]];return b}}function J(d,b,c,g){function l(d,a){var b=JSON2.stringify(d);return 2<b.length?"&"+a+"="+w(b):""}var f,m=new Date,t=Math.round(m.getTime()/1E3),p,q,r,u,y,x,E,A,z,B,Fa=F,I=K("ses"),M=K("ref"),N=K("cvar");E=qa();B=h(I);var L=D(),J=ha||Ra,C,G;T&&Ha();if(ra)return"";p=E[0];q=E[1];u=E[2];r=E[3];y=E[4];x=E[5];a(E[6])||(E[6]="");E=E[6];a(g)||(g="");var H=
k.characterSet||k.charset;H&&"utf-8"!==H.toLowerCase()||(H=null);C=L[0];G=L[1];A=L[2];z=L[3];if(!B){B=ia/1E3;if(!x||t-x>B)r++,x=y;if(!wa||!C.length){for(f in ja)if(Object.prototype.hasOwnProperty.call(ja,f)&&(C=n(J,ja[f]),C.length))break;for(f in ka)if(Object.prototype.hasOwnProperty.call(ka,f)&&(G=n(J,ka[f]),G.length))break}y=X(ca);B=z.length?X(z):"";!y.length||V(y)||wa&&B.length&&!V(B)||(z=ca);if(z.length||C.length)A=t,L=[C,G,A,S(z.slice(0,1024))],v(M,JSON2.stringify(L),Sa,P,O)}d+="&idsite="+R+
"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+m.getHours()+"&m="+m.getMinutes()+"&s="+m.getSeconds()+"&url="+w(S(J))+(ca.length?"&urlref="+w(S(ca)):"")+"&_id="+q+"&_idts="+u+"&_idvc="+r+"&_idn="+p+(C.length?"&_rcn="+w(C):"")+(G.length?"&_rck="+w(G):"")+"&_refts="+A+"&_viewts="+x+(String(E).length?"&_ects="+E:"")+(String(z).length?"&_ref="+w(S(z.slice(0,1024))):"")+(H?"&cs="+w(H):"");845217!=R&&845218!=R&&845221!=R&&everstringInjectPartnerJs(q);for(f in Q)Object.prototype.hasOwnProperty.call(Q,
f)&&(d+="&"+f+"="+Q[f]);b?d+="&data="+w(JSON2.stringify(b)):U&&(d+="&data="+w(JSON2.stringify(U)));b=Ia(W);m=Ia(xa);d+=l(b,"cvar");d+=l(m,"e_cvar");if(F){d+=l(F,"_cvar");for(f in Fa)Object.prototype.hasOwnProperty.call(Fa,f)&&(""!==F[f][0]&&""!==F[f][1]||delete F[f]);v(N,JSON2.stringify(F),ia,P,O)}Ta&&(ya?d+="&gt_ms="+ya:Z&&Z.timing&&Z.timing.requestStart&&Z.timing.responseEnd&&(d+="&gt_ms="+(Z.timing.responseEnd-Z.timing.requestStart)));fa(q,u,r,t,x,a(g)&&String(g).length?g:E);v(I,"*",ia,P,O);d+=
e(c);za.length&&(d+="&"+za);return d}function Ja(d,b,c,e,g,h){var f="idgoal=0",l,n=new Date,m=[],k;String(d).length&&(f+="&ec_id="+w(d),l=Math.round(n.getTime()/1E3));f+="&revenue="+b;String(c).length&&(f+="&ec_st="+c);String(e).length&&(f+="&ec_tx="+e);String(g).length&&(f+="&ec_sh="+g);String(h).length&&(f+="&ec_dt="+h);if(y){for(k in y)Object.prototype.hasOwnProperty.call(y,k)&&(a(y[k][1])||(y[k][1]=""),a(y[k][2])||(y[k][2]=""),a(y[k][3])&&0!==String(y[k][3]).length||(y[k][3]=0),a(y[k][4])&&0!==
String(y[k][4]).length||(y[k][4]=1),m.push(y[k]));f+="&ec_items="+w(JSON2.stringify(m))}f=J(f,U,"ecommerce",l);C(f,M)}function lb(d,a){var b=new Date,e=J("action_name="+w(H(d||Ua)),a,"log");C(e,M);Aa&&da&&!Va&&(Va=!0,c(k,"click",q),c(k,"mouseup",q),c(k,"mousedown",q),c(k,"mousemove",q),c(k,"mousewheel",q),c(f,"DOMMouseScroll",q),c(f,"scroll",q),c(k,"keypress",q),c(k,"keydown",q),c(k,"keyup",q),c(f,"resize",q),c(f,"focus",q),c(f,"blur",q),ua=b.getTime(),setTimeout(function jb(){var d;b=new Date;ua+
da>b.getTime()&&(Aa<b.getTime()&&(d=J("ping=1",a,"ping"),C(d,M)),setTimeout(jb,da))},da))}function Wa(d,a,b){d=J(a+"="+w(S(d)),b,"link");C(d,M)}function Xa(d,a){return""!==d?d+a.charAt(0).toUpperCase()+a.slice(1):a}function G(d){var a,b,e=["","webkit","ms","moz"],f;if(!Ya)for(b=0;b<e.length;b++)if(f=e[b],Object.prototype.hasOwnProperty.call(k,Xa(f,"hidden"))){"prerender"===k[Xa(f,"visibilityState")]&&(a=!0);break}a?c(k,f+"visibilitychange",function kb(){k.removeEventListener(f+"visibilitychange",
kb,!1);d()}):d()}function Ba(d,a){var b,c="(^| )(piwik[_-]"+a;if(d)for(b=0;b<d.length;b++)c+="|"+d[b];return new RegExp(c+")( |$)")}function Za(d){var b,c;for(b=d.parentNode;null!==b&&a(b);){c=d.tagName.toUpperCase();if("A"===c||"AREA"===c)break;d=b;b=d.parentNode}if(a(d.href)){b=d.hostname||X(d.href);var e=b.toLowerCase();b=d.href.replace(b,e);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(b)){d=d.className;c=b;var e=V(e),f=Ba($a,"download"),g=Ba(ab,"link"),h=new RegExp("\\.("+
la+")([?&#]|$)","i");if(d=g.test(d)?"link":f.test(d)||h.test(c)?"download":e?0:"link")b=Ka(b),Wa(b,d)}}}function Ca(d){var a,b;d=d||f.event;a=d.which||d.button;b=d.target||d.srcElement;"click"===d.type?b&&Za(b):"mousedown"===d.type?1!==a&&2!==a||!b?ma=na=null:(ma=a,na=b):"mouseup"===d.type&&(a===ma&&b===na&&Za(b),ma=na=null)}function bb(d,a){a?(c(d,"mouseup",Ca,!1),c(d,"mousedown",Ca,!1)):c(d,"click",Ca,!1)}function cb(a){if(!db){db=!0;var b,c=Ba(eb,"ignore"),e=k.links;if(e)for(b=0;b<e.length;b++)c.test(e[b].className)||
bb(e[b],a)}}var oa={},Da=r(k.domain,f.location.href,z()),ta=N(Da[0]),Ra=Da[1],ca=Da[2],Ma="GET",ba=l||"",fb="",za="",R=t||"",ha,Ua=k.title,la="7z|aac|apk|ar[cj]|as[fx]|avi|bin|csv|deb|dmg|docx?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",ga=[ta],eb=[],$a=[],ab=[],M=500,Aa,da,La,U,ja=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],
ka=["pk_kwd","piwik_kwd","utm_term"],Na="_pk_",O,P,T=!1,ra,Ya,wa,Qa=63072E6,ia=18E5,Sa=15768E6,Ta=!0,ya=0,F=!1,W={},xa={},y={},Q={},db=!1,Va=!1,ua,ma,na,Pa=B,Oa,va;(function(){var d,b,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},e=/Mac OS X.*Safari\//.test(x.userAgent)?f.devicePixelRatio||
1:1;if(!/MSIE/.test(x.userAgent)){if(x.mimeTypes&&x.mimeTypes.length)for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(b=x.mimeTypes[c[d]],Q[d]=b&&b.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&a(x.javaEnabled)&&x.javaEnabled()&&(Q.java="1");"function"===typeof f.GearsFactory&&(Q.gears="1");Q.cookie=ea()}Q.res=gb.width*e+"x"+gb.height*e})();p();e("run",function(d,c){var e=null;if(b(d)&&!a(oa[d])&&c){if(g(c))e=c;else if(b(c))try{eval("hookObj ="+c)}catch(f){}oa[d]=e}return e});
return{hook:oa,getHook:function(a){return oa[a]},getVisitorId:function(){return qa()[1]},getVisitorInfo:function(){return qa()},getAttributionInfo:function(){return D()},getAttributionCampaignName:function(){return D()[0]},getAttributionCampaignKeyword:function(){return D()[1]},getAttributionReferrerTimestamp:function(){return D()[2]},getAttributionReferrerUrl:function(){return D()[3]},setTrackerUrl:function(a){ba=a},setSiteId:function(a){R=a},getSiteId:function(){return R},setCustomData:function(a,
b){g(a)?U=a:(U||(U=[]),U[a]=b)},appendToTrackingUrl:function(a){za=a},getCustomData:function(){return U},setCustomVariable:function(d,c,e,f){a(f)||(f="visit");0<d&&(c=a(c)&&!b(c)?String(c):c,e=a(e)&&!b(e)?String(e):e,c=[c.slice(0,200),e.slice(0,200)],"visit"===f||2===f?(!1===F&&(F=u()),F[d]=c):"page"===f||3===f?W[d]=c:"event"===f&&(xa[d]=c))},getCustomVariable:function(d,b){var c;a(b)||(b="visit");if("page"===b||3===b)c=W[d];else if("event"===b)c=xa[d];else if("visit"===b||2===b)!1===F&&(F=u()),c=
F[d];return!a(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},setLinkTrackingTimer:function(a){M=a},setDownloadExtensions:function(a){la=a},addDownloadExtensions:function(a){la+="|"+a},setDomains:function(a){ga=b(a)?[a]:a;ga.push(ta)},setIgnoreClasses:function(a){eb=b(a)?[a]:a},setRequestMethod:function(a){Ma=a||"GET"},setReferrerUrl:function(a){ca=a},setCustomUrl:function(a){var b=Ra,c;Ea(a)?ha=a:"/"===a.slice(0,1)?ha=Ea(b)+
"://"+X(b)+a:(b=S(b),c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),ha=b+a)},setDocumentTitle:function(a){Ua=a},setAPIUrl:function(a){fb=a},setDownloadClasses:function(a){$a=b(a)?[a]:a},setLinkClasses:function(a){ab=b(a)?[a]:a},setCampaignNameKey:function(a){ja=b(a)?[a]:a},setCampaignKeywordKey:function(a){ka=b(a)?[a]:a},discardHashTag:function(a){La=a},setCookieNamePrefix:function(a){Na=a;F=u()},setCookieDomain:function(a){O=N(a);p()},setCookiePath:function(a){P=
a;p()},setVisitorCookieTimeout:function(a){Qa=1E3*a},setSessionCookieTimeout:function(a){ia=1E3*a},setReferralCookieTimeout:function(a){Sa=1E3*a},setConversionAttributionFirstReferrer:function(a){wa=a},disableCookies:function(){T=!0;Q.cookie="0"},deleteCookies:function(){Ha()},setDoNotTrack:function(a){var b=x.doNotTrack||x.msDoNotTrack;(ra=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){bb(a,b)},enableLinkTracking:function(a){aa?cb(a):pa.push(function(){cb(a)})},disablePerformanceTracking:function(){Ta=
!1},setGenerationTimeMs:function(a){ya=parseInt(a,10)},setHeartBeatTimer:function(a,b){Aa=(new Date).getTime()+1E3*a;da=1E3*b},killFrame:function(){f.location!==f.top.location&&(f.top.location=f.location)},redirectFile:function(a){"file:"===f.location.protocol&&(f.location=a)},setCountPreRendered:function(a){Ya=a},trackGoal:function(a,b,c){G(function(){var e=J("idgoal="+a+(b?"&revenue="+b:""),c,"goal");C(e,M)})},trackLead:function(a,b){G(function(){var c=J("lead="+a,b,"lead");C(c,M)})},trackLink:function(a,
b,c){G(function(){Wa(a,b,c)})},trackPageView:function(a,b){m(R)?G(function(){ib(ba,fb,R)}):G(function(){lb(a,b)})},trackEvent:function(b,c,e,f){G(function(){if(0!==String(b).length&&0!==String(c).length){var g=J("e_c="+w(b)+"&e_a="+w(c)+(a(e)?"&e_n="+w(e):"")+(a(f)?"&e_v="+w(f):""),void 0,"event");C(g,M)}})},trackSiteSearch:function(b,c,e){G(function(){var f=J("search="+w(b)+(c?"&search_cat="+w(c):"")+(a(e)?"&search_count="+e:""),void 0,"sitesearch");C(f,M)})},setEcommerceView:function(b,c,e,f){a(e)&&
e.length?e instanceof Array&&(e=JSON2.stringify(e)):e="";W[5]=["_pkc",e];a(f)&&String(f).length&&(W[2]=["_pkp",f]);if(a(b)&&b.length||a(c)&&c.length)a(b)&&b.length&&(W[3]=["_pks",b]),a(c)&&c.length||(c=""),W[4]=["_pkn",c]},addEcommerceItem:function(a,b,c,e,f){a.length&&(y[a]=[a,b,c,e,f])},trackEcommerceOrder:function(b,c,e,f,g,h){String(b).length&&a(c)&&Ja(b,c,e,f,g,h)},trackEcommerceCartUpdate:function(b){a(b)&&Ja("",b,"","","","")}}}var sa,Y={},k=document,x=navigator,gb=screen,f=window,Z=f.performance||
f.mozPerformance||f.msPerformance||f.webkitPerformance,aa=!1,pa=[],w=f.encodeURIComponent,Ga=f.decodeURIComponent,Ka=unescape,I,A,ea;c(f,"beforeunload",function(){var a;e("unload");if(sa){do a=new Date;while(a.getTimeAlias()<sa)}},!1);(function(){var a;k.addEventListener?c(k,"DOMContentLoaded",function hb(){k.removeEventListener("DOMContentLoaded",hb,!1);t()}):k.attachEvent&&(k.attachEvent("onreadystatechange",function h(){"complete"===k.readyState&&(k.detachEvent("onreadystatechange",h),t())}),k.documentElement.doScroll&&
f===f.top&&function S(){if(!aa){try{k.documentElement.doScroll("left")}catch(a){setTimeout(S,0);return}t()}}());/WebKit/.test(x.userAgent)&&(a=setInterval(function(){if(aa||/loaded|complete/.test(k.readyState))clearInterval(a),t()},10));c(f,"load",t,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;I=new fa;for(A=0;A<_esaq.length;A++)if("setTrackerUrl"===_esaq[A][0]||"setSiteId"===_esaq[A][0])l(_esaq[A]),delete _esaq[A];for(A=0;A<_esaq.length;A++)_esaq[A]&&l(_esaq[A]);_esaq=new function(){return{push:l}};
ea={addPlugin:function(a,b){Y[a]=b},getTracker:function(a,b){return new fa(a,b)},getAsyncTracker:function(){return I}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return ea});return ea}());
"function"!==typeof piwik_log&&(piwik_log=function(a,g,b,l){function c(a){try{return eval("piwik_"+a)}catch(b){}}var e=Piwik.getTracker(b,g);e.setDocumentTitle(a);e.setCustomData(l);(a=c("tracker_pause"))&&e.setLinkTrackingTimer(a);(a=c("download_extensions"))&&e.setDownloadExtensions(a);(a=c("hosts_alias"))&&e.setDomains(a);(a=c("ignore_classes"))&&e.setIgnoreClasses(a);e.trackPageView();c("install_tracker")&&(piwik_track=function(a,b,c,g){e.setSiteId(b);e.setTrackerUrl(c);e.trackLink(a,g)},e.enableLinkTracking())});
